name: Publish Docker Image

on:
  release:
    types: [published]
    
jobs:

  publish:
    name: Build and publish to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: juvenn/letsencrypt-nginx
        tag_with_ref: true
